"""Emoji to text art replacement for devices without emoji font support."""

import re

# Emoji → text art map (common emojis to expressive ASCII equivalents)
_EMOJI_MAP: dict[str, str] = {
    # Smileys
    "😀": ":D",
    "😃": ":D",
    "😄": ":D",
    "😁": "^_^",
    "😆": "xD",
    "😅": "^_^;",
    "🤣": "xDD",
    "😂": "xD",
    "🙂": ":)",
    "🙃": "(:",
    "😉": ";)",
    "😊": "^_^",
    "😇": "o:)",
    "🥰": "(♡_♡)",
    "😍": "(♡_♡)",
    "🤩": "(*_*)",
    "😘": ":*",
    "😗": ":*",
    "😚": ":*",
    "😙": ":*",
    "🥲": ":')",
    "😋": ":P~",
    "😛": ":P",
    "😜": ";P",
    "🤪": ";P",
    "😝": "xP",
    "🤑": "$_$",
    "🤗": ">^_^<",
    "🤭": "*_*",
    "🤫": "shh",
    "🤔": "(?)",
    "🫡": "o7",
    "🤐": ":-X",
    "🤨": "o_O",
    "😐": ":-|",
    "😑": "-_-",
    "😶": ":-|",
    "🫥": "...",
    "😏": ";)",
    "😒": "-_-",
    "🙄": "9_9",
    "😬": ":S",
    "😮‍💨": "-_-;",
    "🤥": ":^)",
    "🫨": "(!)",
    "😌": "~_~",
    "😔": ":(",
    "😪": "(-_-)zzZ",
    "🤤": ":P~~",
    "😴": "(-_-)zzZ",
    "😷": ":-#",
    "🤒": ":-#",
    "🤮": ":X",
    "🤧": "achoo!",
    "🥵": ">_<~",
    "🥶": "brrr",
    "🥴": "@_@",
    "😵": "x_x",
    "😵‍💫": "@_@",
    "🤯": "*!*",
    "🤠": "yee-haw",
    "🥳": "~^_^~",
    "🥸": "8-)",
    "😎": "B-)",
    "🤓": "8-)",
    "🧐": "o_O",
    "😕": ":/",
    "🫤": ":/",
    "😟": ":(",
    "🙁": ":(",
    "😮": ":O",
    "😯": ":O",
    "😲": ":O!",
    "😳": "O_O",
    "🥺": ";_;",
    "🥹": ";_;",
    "😦": "D:",
    "😧": "D:",
    "😨": "D:!",
    "😰": "D:;",
    "😥": ":'(",
    "😢": ":'(",
    "😭": "T_T",
    "😱": "(aah!)",
    "😖": ">_<",
    "😣": ">_<",
    "😞": ":(",
    "😓": "-_-;",
    "😩": "DX",
    "😫": "DX",
    "🥱": "(-o-)",
    "😤": ">_<",
    "😡": ">:(",
    "😠": ">:(",
    "🤬": "#!@$",
    "😈": ">:)",
    "👿": ">:)",
    "💀": "(x_x)",
    "☠️": "(x_x)",
    "💩": "poo",
    "🤡": ":o)",
    "👹": "oni",
    "👻": "boo!",
    "👽": "@_@",
    "🤖": "[o_o]",
    "😺": ":3",
    "😸": ":3",
    "😹": "x3",
    "😻": "<3 :3",
    "🙀": ":O!",
    "😿": ":'3",
    "😾": ">:3",

    # Gestures & people
    "👋": "(wave)",
    "🤚": "(stop)",
    "🖐️": "(hi5)",
    "✋": "(hi5)",
    "🖖": "(V)",
    "🫱": "->",
    "🫲": "<-",
    "👌": "(ok)",
    "🤌": "(!)",
    "🤏": "(tiny)",
    "✌️": "(V)",
    "🤞": "(luck)",
    "🫰": "(snap)",
    "🤟": "\\m/",
    "🤘": "\\m/",
    "🤙": "(call)",
    "👈": "<-",
    "👉": "->",
    "👈🏼": "<-",
    "👉🏼": "->",
    "👆": "^",
    "👇": "v",
    "☝️": "^",
    "🫵": "(you)",
    "👍": "(+1)",
    "👍🏼": "(+1)",
    "👎": "(-1)",
    "👎🏼": "(-1)",
    "✊": "(fist)",
    "👊": "(bump)",
    "🤛": "(bump)",
    "🤜": "(bump)",
    "👏": "(clap)",
    "🙌": "\\o/",
    "🫶": "<3",
    "👐": "(open)",
    "🤲": "(please)",
    "🤝": "(deal)",
    "🙏": "(pray)",
    "✍️": "(write)",
    "💪": "(flex)",
    "🦾": "(flex)",
    "🫂": "(hug)",
    "🤷": "(?_?)",
    "🤷‍♂️": "(?_?)",
    "🤷‍♀️": "(?_?)",
    "🤦": "(facepalm)",
    "🤦‍♂️": "(facepalm)",
    "🤦‍♀️": "(facepalm)",

    # Hearts & emotions
    "❤️": "<3",
    "🧡": "<3",
    "💛": "<3",
    "💚": "<3",
    "💙": "<3",
    "💜": "<3",
    "🖤": "<3",
    "🤍": "<3",
    "🤎": "<3",
    "💔": "</3",
    "❤️‍🔥": "<3!",
    "❣️": "<3",
    "💕": "<3<3",
    "💞": "<3<3",
    "💓": "<3",
    "💗": "<3",
    "💖": "<3*",
    "💘": "<-3",
    "💝": "<3",
    "💟": "<3",
    "♥️": "<3",
    "💋": "xo",
    "💯": "100!",
    "💢": "(!)",
    "💥": "*boom*",
    "💫": "*~*",
    "💦": ";;",
    "💨": "~>",
    "💬": "...",
    "💭": "(..)",
    "🗯️": "(!)",

    # Celebrations & objects
    "🎉": "*party*",
    "🎊": "*party*",
    "🎈": "(o)",
    "🎁": "[gift]",
    "🎂": "[cake]",
    "🍰": "[cake]",
    "🎄": "[tree]",
    "🎃": "[pumpkin]",
    "🎆": "*boom*",
    "🎇": "*sparkle*",
    "✨": "*",
    "🌟": "*",
    "⭐": "*",
    "🌈": "(rainbow)",
    "🔥": "*fire*",
    "💡": "(!)",
    "🎵": "~♪~",
    "🎶": "~♪♪~",
    "🎤": "(mic)",
    "🎸": "(guitar)",
    "🏆": "[trophy]",
    "🥇": "[1st]",
    "🥈": "[2nd]",
    "🥉": "[3rd]",
    "🏅": "[medal]",
    "⚽": "(ball)",
    "🏀": "(ball)",
    "🎯": "(bullseye)",
    "🎮": "(game)",
    "🧩": "(puzzle)",
    "📱": "(phone)",
    "💻": "(laptop)",
    "⌨️": "(kbd)",
    "🖥️": "(pc)",
    "📷": "(cam)",
    "📸": "(cam)",
    "📞": "(call)",
    "📧": "(mail)",
    "📝": "(note)",
    "📌": "(pin)",
    "📎": "(clip)",
    "✏️": "(edit)",
    "📅": "(cal)",
    "⏰": "(alarm)",
    "⏳": "(time)",
    "🔑": "(key)",
    "🔒": "(lock)",
    "🔓": "(unlock)",

    # Food & drink
    "☕": "(coffee)",
    "🍺": "(beer)",
    "🍻": "(cheers)",
    "🍷": "(wine)",
    "🍸": "(drink)",
    "🍕": "(pizza)",
    "🍔": "(burger)",
    "🌮": "(taco)",
    "🍣": "(sushi)",
    "🍩": "(donut)",
    "🍪": "(cookie)",
    "🍫": "(choco)",
    "🍿": "(popcorn)",

    # Nature & weather
    "☀️": "(*)",
    "🌙": "(moon)",
    "⛅": "(cloud)",
    "🌧️": "(rain)",
    "⛈️": "(storm)",
    "❄️": "*snow*",
    "🌊": "(wave)",
    "🌸": "(flower)",
    "🌺": "(flower)",
    "🌻": "(flower)",
    "🌹": "(rose)",
    "🍀": "(clover)",
    "🍁": "(leaf)",
    "🌴": "(palm)",
    "🐶": "(dog)",
    "🐱": "(cat)",
    "🐻": "(bear)",
    "🦊": "(fox)",
    "🐸": "(frog)",
    "🐔": "(chicken)",
    "🦄": "(unicorn)",
    "🐝": "(bee)",
    "🦋": "(butterfly)",

    # Symbols & marks
    "✅": "[ok]",
    "❌": "[x]",
    "⚠️": "[!]",
    "🚫": "[no]",
    "❓": "(?)",
    "❗": "(!)",
    "‼️": "(!!)",
    "⁉️": "(?!)",
    "💤": "zzZ",
    "🆗": "[ok]",
    "🆕": "[new]",
    "🆘": "[SOS]",
    "📍": "(here)",
    "🏠": "(home)",
    "🚗": "(car)",
    "✈️": "(plane)",
    "🚀": "(rocket)",
    "⬆️": "^",
    "⬇️": "v",
    "⬅️": "<-",
    "➡️": "->",
    "↩️": "<-",
    "↪️": "->",
    "🔄": "(reload)",
    "➕": "+",
    "➖": "-",
    "✖️": "x",
    "➗": "/",
    "♻️": "(recycle)",
    "©️": "(c)",
    "®️": "(r)",
    "™️": "(tm)",
}

# Build a regex pattern that matches any emoji in the map (longest first)
_EMOJI_PATTERN = re.compile(
    "|".join(re.escape(k) for k in sorted(_EMOJI_MAP.keys(), key=len, reverse=True))
)

# Pattern to match remaining emoji Unicode ranges not in our map
_UNKNOWN_EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F300-\U0001F5FF"  # misc symbols & pictographs
    "\U0001F680-\U0001F6FF"  # transport & map
    "\U0001F700-\U0001F77F"  # alchemical
    "\U0001F780-\U0001F7FF"  # geometric shapes ext
    "\U0001F800-\U0001F8FF"  # supplemental arrows-C
    "\U0001F900-\U0001F9FF"  # supplemental symbols
    "\U0001FA00-\U0001FA6F"  # chess symbols
    "\U0001FA70-\U0001FAFF"  # symbols ext-A
    "\U00002702-\U000027B0"  # dingbats
    "\U0000FE00-\U0000FE0F"  # variation selectors
    "\U0000200D"             # zero-width joiner
    "\U000020E3"             # combining enclosing keycap
    "\U00002600-\U000026FF"  # misc symbols
    "\U00002300-\U000023FF"  # misc technical
    "\U0000231A-\U0000231B"  # watch/hourglass
    "\U00002934-\U00002935"  # arrows
    "\U000025AA-\U000025FE"  # geometric shapes
    "\U00002B05-\U00002B55"  # arrows & symbols
    "\U0001F1E0-\U0001F1FF"  # flags
    "]+"
)


def replace_emojis(text: str) -> str:
    """Replace emojis with text art equivalents.

    Known emojis get expressive ASCII replacements.
    Unknown emojis are stripped (removed silently).
    If the result would be empty, returns '(emoji)'.
    """
    # First pass: replace known emojis with text art
    result = _EMOJI_PATTERN.sub(lambda m: _EMOJI_MAP[m.group()], text)

    # Second pass: strip any remaining unknown emojis
    result = _UNKNOWN_EMOJI_PATTERN.sub("", result)

    # Clean up: collapse multiple spaces, strip
    result = re.sub(r"  +", " ", result).strip()

    # If the entire message was emoji and nothing remains
    if not result:
        return "(emoji)"

    return result
