#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "src"))
from server import main

main()
