
; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	bodmer/TFT_eSPI@^2.5.0
	kublet/KGFX@^0.0.22
	kublet/OTAServer@^1.0.4
	Bodmer/TJpg_Decoder@^1.1.0
monitor_speed = 460800
